### ISSUE TITLE
Change font size in the search page

### ISSUE THREAD

**Issue by quriousxr** [FooSoft/yomichan#1103]
Is there any way to change the font size in the search page? Not the pop up dictionaries but _the text copied from the clipboard monitor_. My apologies if I there is an obvious option I have missed.

**Comment by toasted-nutbread** [comment]
Assuming you want to make the font size smaller, edit the custom CSS option:

Before version 20.12.6.0:
```css
#query-parser-content { font-size: 1em; }
```

For version 20.12.6.0 and above:
```css
:root { --query-parser-font-size-no-units: 1; }
```

2 is the default value (large text); 1 is regular sized text; value can be a decimal if you want something in between.
