### ISSUE TITLE
[Feature Request] Colour headword based on pitch accent

### ISSUE THREAD

**Issue by stegatxins0** [FooSoft/yomichan#1459]
[Migaku Japanse](https://github.com/migaku-official/Migaku-Japanese-Addon) have a feature to color word based on their pitch accent. With the pitch accent update, is it possible to implement this but for headword in yomichan?  [This](https://www.migaku.io/tools-guides/migaku-japanese/quickstart/#pitch-accent-patterns) explains how the coloring works.
![](https://i.imgur.com/HkngdK2.png)(頭高)[1]

I have a javascript function in Anki which take the pitch accent position number as input and colour bold word. However, since I don't know any dictionary that tell me if the word is verb or noun, I have to manually configure it. 

```javascript
function markPitch() {
    const heiban = "blue";
    const atamadaka= "red";
    const nakadaka = "orange";
    const odaka = "green";
    const kifuku = "purple";
		const pitchNumber = "{{pitchpos}}";

		/* Pitch number is always one digit. Exit otherwise. */
		if (pitchNumber.length != 1)
			return;

   {{#verb}}
		if (pitchNumber == 0) {
			paintBolds(heiban); 
		} else {
			paintBolds(kifuku); 
		}	
			return;
   {{/verb}}
   

		if ( pitchNumber == 0 )  {
			paintBolds(heiban);
		} else if ( pitchNumber == 1 ) {
			paintBolds(atamadaka);
		} else if ( pitchNumber > 1 ) {
			if ( odakanaka(pitchNumber) ) {
				paintBolds(odaka);
			} else {
				paintBolds(nakadaka);
			}
		}
	}
	function paintBolds(color) {
		const jpElements = document.getElementsByClassName("pitchcolor");
		for ( i = 0; i < jpElements.length; i++ ) {
			const boldElements = jpElements[i].getElementsByTagName("b");
			for ( j = 0; j < boldElements.length; j++ ) {
				if ( boldElements[j] ) { boldElements[j].style.color = color; }
			}
 			
		}
	}

	function odakanaka(pitchNumber) {
		// small っ is one mora; ゃゅょ are parts of single mora
		const kanaWord = "{{kana:ふりがな}}".replace(/[ャュョゃゅょ]/g, '');
		if ( kanaWord.length == pitchNumber ) {
			return true;
		} else {
			return false;
		}
	}
```
I noticed that you can set custom CSS in yomichan. Is it possible to add function similar to above?

**Comment by toasted-nutbread** [comment]
> With the pitch accent update, is it possible to implement this but for headword in yomichan?

Maybe, it depends on what you expect. Pitch accent dictionaries can expose multiple pitch options for a single word, so that could make the display ambiguous or misleading.

> However, since I don't know any dictionary that tell me if the word is verb or noun, I have to manually configure it.

This info is in the tags, verbs usually have a `v1`, `v5`, `vk`, `vs`, or `vz` entry.

**Comment by toasted-nutbread** [comment]
This will be implemented in the next release, except for kifuku, since that requires some additional changes to the exposed data in order to more accurately get part of speech (which also will help better address your other issue).

The change made exposes a `data-pitch-accent-categories` attribute on the element with the `expression` class. This can be used to write rules which modify the colors. Note that this attribute can have multiple values, which are space separated.

Example CSS:
```css
.expression[data-pitch-accent-categories~=heiban] {
    --expression-current-text-color: blue !important;
    --expression-current-kanji-text-color: blue !important;
    --expression-current-reading-text-color: blue !important;
    --expression-current-furigana-text-color: blue !important;
}

.expression[data-pitch-accent-categories~=atamadaka] {
    --expression-current-text-color: red !important;
    --expression-current-kanji-text-color: red !important;
    --expression-current-reading-text-color: red !important;
    --expression-current-furigana-text-color: red !important;
}

.expression[data-pitch-accent-categories~=nakadaka] {
    --expression-current-text-color: orange !important;
    --expression-current-kanji-text-color: orange !important;
    --expression-current-reading-text-color: orange !important;
    --expression-current-furigana-text-color: orange !important;
}

.expression[data-pitch-accent-categories~=odaka] {
    --expression-current-text-color: green !important;
    --expression-current-kanji-text-color: green !important;
    --expression-current-reading-text-color: green !important;
    --expression-current-furigana-text-color: green !important;
}

.expression[data-pitch-accent-categories~=kifuku] {
    --expression-current-text-color: purple !important;
    --expression-current-kanji-text-color: purple !important;
    --expression-current-reading-text-color: purple !important;
    --expression-current-furigana-text-color: purple !important;
}

/* Example rule for case when a term has multiple types of pitch accent categorizations. */
.expression[data-pitch-accent-categories*=' '] {
    --expression-current-text-color: cyan !important;
    --expression-current-kanji-text-color: cyan !important;
    --expression-current-reading-text-color: cyan !important;
    --expression-current-furigana-text-color: cyan !important;
}
```

**Comment by stegatxins0** [comment]
> This info is in the tags, verbs usually have a v1, v5, vk, vs, or vz entry.

Can someone guide me through how to export this to a specified field in Anki through handlebar? Or provide some resources on this? I'm not familiar with how dictionary works.

> This will be implemented in the next release, except for kifuku, since that requires some additional changes to the exposed data in order to more accurately get part of speech (which also will help better address your other issue).

I agree. This would need changes to the current data. The way I see this is that there is two possible options:
- make changes to current pitch accent dictionary to include such data
- again, get word classes information from current dictionary, although I'm not sure how this would work

With that being said, kifuku is not in the main pitch accent so it's completely optional. But it would be nice to provide a workaround for it.  Thank you for implementing this feature so quick.

**Comment by Thermospore** [comment]
> Pitch accent dictionaries can expose multiple pitch options for a single word, so that could make the display ambiguous or misleading.

Here is how the addon handles that, just by adding a diamond for each of the additional patterns after
![image](https://user-images.githubusercontent.com/35350819/109455673-96e4ce00-7a03-11eb-828b-d97255aa74c4.png)

**Comment by archiif** [comment]
Is this in the latest version already? I tried exporting a word to Anki but I see no new attribute within any of the resulting fields in Anki.

**Comment by toasted-nutbread** [comment]
The information was added to the HTML display of results within the extension, the Anki functionality wasn't changed. Pitch accent position info is currently exposed, so that can technically be used if you know how to set up handlebars templates. Beyond that, there are already some Anki field markers for displaying pitch accents, look for `{pitch-accent*}`.

**Comment by archiif** [comment]
Yeah thanks for the info, deleted my message hastily when I realized it, sorry about that.

**Comment by archiif** [comment]
Sorry for bumping this issue again, but I don't know where else to ask.
@stegatxins0 How did you implement detection of verbs and adjectives for kifuku on Anki? I managed to get the 4 standard coloring to work with the function, but I'm not sure how to add support for kifuku.

**Comment by toasted-nutbread** [comment]
> I managed to get the 4 standard coloring to work with the function, but I'm not sure how to add support for kifuku.

From what I gathered, it sounded like it was a manual process, but related below:

> Can someone guide me through how to export this to a specified field in Anki through handlebar? Or provide some resources on this? I'm not familiar with how dictionary works.

Also, I never explicitly answered this, because as I started to look into it, it turned out to be more convoluted than I would have liked. I'm aiming to expose better part-of-speech information in a future release, so stay tuned for that.

**Comment by archiif** [comment]
Thanks, that's an interesting approach. Looking at the tags seems like a viable method too, I'll also try to give that a spin.

>Also, I never explicitly answered this, because as I started to look into it, it turned out to be more convoluted than I would have liked. I'm aiming to expose better part-of-speech information in a future release, so stay tuned for that.

Looking forward to this too.

**Comment by toasted-nutbread** [comment]
FYI: #1561 adds a `{part-of-speech}` marker, and part of speech information is now used to add the `kifuku` attribute to the dictionary entry HTML.

**Comment by stegatxins0** [comment]
> The information was added to the HTML display of results within the extension, the Anki functionality wasn't changed. Pitch accent position info is currently exposed, so that can technically be used if you know how to set up handlebars templates. Beyond that, there are already some Anki field markers for displaying pitch accents, look for `{pitch-accent*}`.

@toasted-nutbread I'm not familiar with handlebars. Would you mind sharing the handlebars code for anki templates for pitch accent categories so that `{pitch-accent-categories}` will return `heiban` or `kifuku` in anki field?

**Comment by toasted-nutbread** [comment]
To spare everyone a ~100 line handlebars template, I'll be adding a helper (#1459) to generate this info. The template which uses the helper will look like:
```handlebars
{{#*inline "pitch-accent-categories"}}
    {{~#each (pitchCategories .)~}}
        {{.}}{{#unless @last}}, {{/unless}}
    {{~/each~}}
{{/inline}}
```

**Comment by toasted-nutbread** [comment]
Note: #1850 changes some of the CSS rules mentioned in https://github.com/FooSoft/yomichan/issues/1459#issuecomment-787500329. This change will be included in the July 2021 release.

`data-pitch-accent-categories` has been changed to `data-pronunciation-categories`.

Updated example CSS:
```css
.expression[data-pronunciation-categories~=heiban] {
    --expression-current-text-color: blue !important;
    --expression-current-kanji-text-color: blue !important;
    --expression-current-reading-text-color: blue !important;
    --expression-current-furigana-text-color: blue !important;
}

.expression[data-pronunciation-categories~=atamadaka] {
    --expression-current-text-color: red !important;
    --expression-current-kanji-text-color: red !important;
    --expression-current-reading-text-color: red !important;
    --expression-current-furigana-text-color: red !important;
}

.expression[data-pronunciation-categories~=nakadaka] {
    --expression-current-text-color: orange !important;
    --expression-current-kanji-text-color: orange !important;
    --expression-current-reading-text-color: orange !important;
    --expression-current-furigana-text-color: orange !important;
}

.expression[data-pronunciation-categories~=odaka] {
    --expression-current-text-color: green !important;
    --expression-current-kanji-text-color: green !important;
    --expression-current-reading-text-color: green !important;
    --expression-current-furigana-text-color: green !important;
}

.expression[data-pronunciation-categories~=kifuku] {
    --expression-current-text-color: purple !important;
    --expression-current-kanji-text-color: purple !important;
    --expression-current-reading-text-color: purple !important;
    --expression-current-furigana-text-color: purple !important;
}

/* Example rule for case when a term has multiple types of pitch accent categorizations. */
.expression[data-pronunciation-categories*=' '] {
    --expression-current-text-color: cyan !important;
    --expression-current-kanji-text-color: cyan !important;
    --expression-current-reading-text-color: cyan !important;
    --expression-current-furigana-text-color: cyan !important;
}
```
