### ISSUE TITLE
[Feature Request]  Search windows - width customizable

### ISSUE THREAD

**Issue by grospoulpe** [FooSoft/yomichan#1518]
I would be nice to be able to change the width (see below, for an example)
I usually zoom 200% (4k display, 28 inches), but there still enough room on the left/right sides to put some content.
In fact, when using the pop-up window, the width is adapting itself according to the content, but on the search window, the width is fixed, it seems

Thanks in advance! :)

![2021-03-11 yomichan width](https://user-images.githubusercontent.com/67185866/110750511-dfda2500-8242-11eb-81c0-85c3fbdbd347.png)

**Comment by toasted-nutbread** [comment]
Add something like this to the _Configure custom CSS…_ option (enable _Advanced_):

```css
:root {
    --main-content-size: calc(1200em / var(--font-size-no-units));
}
```

1200 is the width, in pixels; you can change that to whatever value you like (keep the _em_ suffix attached to the number).

**Comment by grospoulpe** [comment]
Thank you very much; works great (I left 1200em, and it's good enough :) )
So, now, with 200% zoom, on a 2560x1440 display, almost all width is used :)

**Comment by toasted-nutbread** [comment]
Note that for future simplicity, I have made a change to the CSS variable name which controls width, so you may have to update your CSS in the future. The new code for versions after 21.2.28.2 will be:
```css
:root {
    --content-width-search: 1200;
}
```

If you want, you can assign both values now and when the update happens in the future, it will be compatible:
```css
:root {
    --main-content-size: calc(1200em / var(--font-size-no-units));
    --content-width-search: 1200;
}
```
