### ISSUE TITLE
How can I hide the scrollbar in the search page?

### ISSUE THREAD

**Issue by quriousxr** [FooSoft/yomichan#1598]
Previously I put this `:root{ scrollbar-width: none !important }` in the CSS, but for some reason it does not work anymore.  Is there any way to hide the scrollbar now?

**Comment by toasted-nutbread** [comment]
```css
/* Firefox */
.content-scroll {
  scrollbar-width: none;
}
/* Chrome */
.content-scroll::-webkit-scrollbar {
  width: 0;
}
```
