### ISSUE TITLE
[Feature Request] Blurry image on resized image, may require more options

### ISSUE THREAD

**Issue by ttu-ttu** [FooSoft/yomichan#1732]
So I've tried implementing gaiji with the new structured-content on `21.5.31.0`, and I've realized that Chrome's default resize algorithm doesn't resize gaiji well.

For instance I've tried converting this specific [daijisen entry](https://www.weblio.jp/content/%E3%81%8A%E3%81%BC%E3%81%A8%E3%82%8B) to Yomichan.

![image](https://user-images.githubusercontent.com/83872826/120927445-6653b500-c713-11eb-96a7-c21c8defecdf.png)

With or without `pixelated` attribute, the image seem to look pretty bad after getting downscaled.

I've also noticed that Yomichan uses this CSS rule set for "pixelated" option:

```css
.gloss-image[data-pixelated=true] {
    image-rendering: auto;
    image-rendering: -moz-crisp-edges;
    image-rendering: -webkit-optimize-contrast;
    image-rendering: pixelated;
    image-rendering: crisp-edges;
}
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering), `pixelated` and `crisp-edges` are used for different purposes, and for Chrome, the property value for `crisp-edges` is `-webkit-optimize-contrast`, which I believe Yomichan's CSS rules may have mixed them up.

I've also tried writing a simple HTML file to test the difference in display for Chrome.

![image](https://user-images.githubusercontent.com/83872826/120927776-a8312b00-c714-11eb-87e3-251c83ee4b56.png)
([will-change](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) is just an alternative solution I've found online)

Anyway, I believe there should be an option other than "pixelated" (or revamp it) to deal with cases like these.
