### ISSUE TITLE
custom css

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#192]
I played around with custom css a little bit, but didn't get how to change fonts for definitions and words that I'm looking up
Need help 👍

**Comment by siikamiika** [comment]
Just in case you didn't try refreshing the page after doing changes, try that first.

Otherwise, here are some examples:
```css
/* Different styles for the headword(s) */
.expression {
  font-size: 50px; /* make words huge */
  font-family: Noto Serif CJK JP; /* change font */
}

/* Different styles for the glossary */
.glossary-item {
  color: red; /* Make glossary red */
}
```
Results in...
![2019-08-28_22-50-28](https://user-images.githubusercontent.com/5602483/63887835-53606c80-c9e6-11e9-9399-3b8a2ba64b12.png)
