### ISSUE TITLE
yomichan pitch styling

### ISSUE THREAD

**Issue by ChubYee** [FooSoft/yomichan#2179]
I'm completely new to yomichan and coding. How would I make the pitch accent line color red instead of white? And is there a way to make the vertical distance of the line more even with the horizontal distance? I've been using an app called jidoujisho for mining, but have switch to PC and am just very used to it's styling, so basically I just want yomichan styling to be like it. 
![Captdure](https://user-images.githubusercontent.com/104586776/174462261-a82c58ec-875c-4d0a-a786-ef39fc7c3464.PNG)
![Capture](https://user-images.githubusercontent.com/104586776/174462262-75fdd9d3-c129-4114-92b3-a55224000bfc.PNG)

**Comment by ChubYee** [comment]
Also, is there a way to modify how the dictionary information looks and is styled when it is exported an anki card? I basically want it so it has:

• ";" after a word (no space) instead of "|"
• no dictionary info (the things in paranthesis like "adj-na", "uk", "JMdict (English)")
• center-aligned text instead of left-aligned

![ideal template](https://user-images.githubusercontent.com/104586776/174463383-561d9eda-8dfd-4fb4-97c4-93e2a8c4d100.PNG)
![yomichan template](https://user-images.githubusercontent.com/104586776/174463385-dc924560-246e-4d02-88ac-dd1a22677b7d.PNG)

**Comment by toasted-nutbread** [comment]
1. There's not a great way to do this, but this kinda works: <br>
   Enable _Advanced, open _Configure Anki card templates…_, and find and change the following template:
   ```css
   {{#*inline "pitch-accents"}}
       {{~> pitch-accent-list format='text'~}}
   {{/inline}}
   ```
   To:
   ```css
   {{#*inline "pitch-accents"}}
       {{~> pitch-accent-list format='text'~}}
   <style>
   span[style*="border-color:currentColor"] {
     border-color: #ff0000 !important;
   }
   span[style*="border-color:currentColor"][style*="height:"] {
     right: -0.1em !important;
     height: auto !important;
     bottom: 0 !important;
   }
   </style>
   {{/inline}}
   ```
2. The `|` can be changed in `{{#*inline "glossary-single"}}`
   ```handlebars
   # Line 26
   {{#each glossary}}{{#formatGlossary ../dictionary}}{{{.}}}{{/formatGlossary}}{{#unless @last}} | {{/unless}}{{/each}}
                                                                                       Right here ^
   ```
3. Change the `<ol>`/`</ol>` tags to `<ul>`/`</ul>` in `{{~#*inline "glossary"~}}` and change your Anki field template from `{glossary}` to `{glossary-brief}`.
4. Change `<div style="text-align: left;">` to `<div style="text-align: center;">` in `{{~#*inline "glossary"~}}`.
