### ISSUE TITLE
[Feature Request] Add option to enable dark mode

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#249]
Just a suggestion: a dark mode for reading at night to be easier on the eyes.

I will be implementing this in the popup only for now, options page will come later. If anyone else wants to give it a shot too, please do because I'm not as skilled as the main developers of Yomichan.

**Comment by oudajosefu** [comment]
Until I add this ability (which might take some time due to my schedule), anyone wanting this now can just add this custom css to the custom css popup input box in the options page:
```css
body {
    color: #fff;
    background: #000;
}
.expression .kanji-link {
    color: rgb(191, 191, 191);
}
.glossary-item {
    color: #fff;
}
```
