### ISSUE TITLE
Is it possible to modify Dictionary's inside Yomichan or export dictionary's to excel?

### ISSUE THREAD

**Issue by 511141** [FooSoft/yomichan#599]
Daijirin is presently being utilized as a dictionary for J-J descriptions. 
However, Daijirin also translates English words and letters to Japanese. 
My query is is it possible to modify the dictionaries inside Yomichan to not show any translations of English letters or 和英 translations.
If not is it possible to export the dictionary database to excel through Yomichan?

**Comment by siikamiika** [comment]
It's possible to disable scanning alphanumeric text in Scanning Options.

和英 translations are harder to disable unless there's some indication of those in the original dictionary that you can check with [Yomichan Import](https://github.com/FooSoft/yomichan-import). It's possible to export the dictionaries to Excel if you know how to convert the JSON files inside the zip to CSV, but I wouldn't recommend that unless you have a way of detecting the English rows (such as guessing it from the proportion of Latin letters, which could be tricky in Excel).

Another hacky solution would be to use Custom popup CSS to hide all English characters within 大辞林, but you'd also need a custom invisible font for that:

```css
@font-face {
  font-family: 'EnglishText';
  src: local('Name Of The Invisible Font');
  unicode-range: U+0061-U+007a;
}

.term-definition-item[data-dictionary=大辞林] .term-glossary-list {
  font-family: EnglishText, sans-serif;
}
```
